// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/communication/v1/orchestration.proto

package communicationv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VendorEmailReceived_VisualizationStage int32

const (
	VendorEmailReceived_VISUALIZATION_STAGE_UNSPECIFIED   VendorEmailReceived_VisualizationStage = 0
	VendorEmailReceived_VISUALIZATION_STAGE_INGESTED      VendorEmailReceived_VisualizationStage = 1
	VendorEmailReceived_VISUALIZATION_STAGE_CLASSIFIED    VendorEmailReceived_VisualizationStage = 2
	VendorEmailReceived_VISUALIZATION_STAGE_ORCHESTRATING VendorEmailReceived_VisualizationStage = 3
)

// Enum value maps for VendorEmailReceived_VisualizationStage.
var (
	VendorEmailReceived_VisualizationStage_name = map[int32]string{
		0: "VISUALIZATION_STAGE_UNSPECIFIED",
		1: "VISUALIZATION_STAGE_INGESTED",
		2: "VISUALIZATION_STAGE_CLASSIFIED",
		3: "VISUALIZATION_STAGE_ORCHESTRATING",
	}
	VendorEmailReceived_VisualizationStage_value = map[string]int32{
		"VISUALIZATION_STAGE_UNSPECIFIED":   0,
		"VISUALIZATION_STAGE_INGESTED":      1,
		"VISUALIZATION_STAGE_CLASSIFIED":    2,
		"VISUALIZATION_STAGE_ORCHESTRATING": 3,
	}
)

func (x VendorEmailReceived_VisualizationStage) Enum() *VendorEmailReceived_VisualizationStage {
	p := new(VendorEmailReceived_VisualizationStage)
	*p = x
	return p
}

func (x VendorEmailReceived_VisualizationStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VendorEmailReceived_VisualizationStage) Descriptor() protoreflect.EnumDescriptor {
	return file_events_communication_v1_orchestration_proto_enumTypes[0].Descriptor()
}

func (VendorEmailReceived_VisualizationStage) Type() protoreflect.EnumType {
	return &file_events_communication_v1_orchestration_proto_enumTypes[0]
}

func (x VendorEmailReceived_VisualizationStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VendorEmailReceived_VisualizationStage.Descriptor instead.
func (VendorEmailReceived_VisualizationStage) EnumDescriptor() ([]byte, []int) {
	return file_events_communication_v1_orchestration_proto_rawDescGZIP(), []int{1, 0}
}

type VendorEmailReceived_Intent int32

const (
	VendorEmailReceived_INTENT_UNSPECIFIED            VendorEmailReceived_Intent = 0
	VendorEmailReceived_INTENT_INVOICE_SUBMISSION     VendorEmailReceived_Intent = 1
	VendorEmailReceived_INTENT_PAYMENT_DISPUTE        VendorEmailReceived_Intent = 2
	VendorEmailReceived_INTENT_PURCHASE_ORDER_INQUIRY VendorEmailReceived_Intent = 3
	VendorEmailReceived_INTENT_GENERAL_SUPPORT        VendorEmailReceived_Intent = 4
)

// Enum value maps for VendorEmailReceived_Intent.
var (
	VendorEmailReceived_Intent_name = map[int32]string{
		0: "INTENT_UNSPECIFIED",
		1: "INTENT_INVOICE_SUBMISSION",
		2: "INTENT_PAYMENT_DISPUTE",
		3: "INTENT_PURCHASE_ORDER_INQUIRY",
		4: "INTENT_GENERAL_SUPPORT",
	}
	VendorEmailReceived_Intent_value = map[string]int32{
		"INTENT_UNSPECIFIED":            0,
		"INTENT_INVOICE_SUBMISSION":     1,
		"INTENT_PAYMENT_DISPUTE":        2,
		"INTENT_PURCHASE_ORDER_INQUIRY": 3,
		"INTENT_GENERAL_SUPPORT":        4,
	}
)

func (x VendorEmailReceived_Intent) Enum() *VendorEmailReceived_Intent {
	p := new(VendorEmailReceived_Intent)
	*p = x
	return p
}

func (x VendorEmailReceived_Intent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VendorEmailReceived_Intent) Descriptor() protoreflect.EnumDescriptor {
	return file_events_communication_v1_orchestration_proto_enumTypes[1].Descriptor()
}

func (VendorEmailReceived_Intent) Type() protoreflect.EnumType {
	return &file_events_communication_v1_orchestration_proto_enumTypes[1]
}

func (x VendorEmailReceived_Intent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VendorEmailReceived_Intent.Descriptor instead.
func (VendorEmailReceived_Intent) EnumDescriptor() ([]byte, []int) {
	return file_events_communication_v1_orchestration_proto_rawDescGZIP(), []int{1, 1}
}

type Attachment struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FileName         string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType         string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SecureStorageUri string                 `protobuf:"bytes,3,opt,name=secure_storage_uri,json=secureStorageUri,proto3" json:"secure_storage_uri,omitempty"`
	Sha256Hash       string                 `protobuf:"bytes,4,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_events_communication_v1_orchestration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_events_communication_v1_orchestration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_events_communication_v1_orchestration_proto_rawDescGZIP(), []int{0}
}

func (x *Attachment) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Attachment) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Attachment) GetSecureStorageUri() string {
	if x != nil {
		return x.SecureStorageUri
	}
	return ""
}

func (x *Attachment) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

type VendorEmailReceived struct {
	state                protoimpl.MessageState                 `protogen:"open.v1"`
	EventId              string                                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TraceParent          string                                 `protobuf:"bytes,2,opt,name=trace_parent,json=traceParent,proto3" json:"trace_parent,omitempty"`
	AggregateId          string                                 `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	OccurredAt           *timestamppb.Timestamp                 `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	PublishedAt          *timestamppb.Timestamp                 `protobuf:"bytes,5,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CdcEmitTs            *timestamppb.Timestamp                 `protobuf:"bytes,6,opt,name=cdc_emit_ts,json=cdcEmitTs,proto3" json:"cdc_emit_ts,omitempty"`
	SequenceEngineKey    uint64                                 `protobuf:"varint,7,opt,name=sequence_engine_key,json=sequenceEngineKey,proto3" json:"sequence_engine_key,omitempty"`
	VisualizationStage   VendorEmailReceived_VisualizationStage `protobuf:"varint,8,opt,name=visualization_stage,json=visualizationStage,proto3,enum=omniflow.communication.v1.VendorEmailReceived_VisualizationStage" json:"visualization_stage,omitempty"`
	IntentClassification VendorEmailReceived_Intent             `protobuf:"varint,9,opt,name=intent_classification,json=intentClassification,proto3,enum=omniflow.communication.v1.VendorEmailReceived_Intent" json:"intent_classification,omitempty"`
	VendorEmail          string                                 `protobuf:"bytes,10,opt,name=vendor_email,json=vendorEmail,proto3" json:"vendor_email,omitempty"`
	MdmVendorId          string                                 `protobuf:"bytes,11,opt,name=mdm_vendor_id,json=mdmVendorId,proto3" json:"mdm_vendor_id,omitempty"`
	SecureSubjectUri     string                                 `protobuf:"bytes,12,opt,name=secure_subject_uri,json=secureSubjectUri,proto3" json:"secure_subject_uri,omitempty"`
	SecureBodyUri        string                                 `protobuf:"bytes,13,opt,name=secure_body_uri,json=secureBodyUri,proto3" json:"secure_body_uri,omitempty"`
	Attachments          []*Attachment                          `protobuf:"bytes,14,rep,name=attachments,proto3" json:"attachments,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *VendorEmailReceived) Reset() {
	*x = VendorEmailReceived{}
	mi := &file_events_communication_v1_orchestration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorEmailReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorEmailReceived) ProtoMessage() {}

func (x *VendorEmailReceived) ProtoReflect() protoreflect.Message {
	mi := &file_events_communication_v1_orchestration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorEmailReceived.ProtoReflect.Descriptor instead.
func (*VendorEmailReceived) Descriptor() ([]byte, []int) {
	return file_events_communication_v1_orchestration_proto_rawDescGZIP(), []int{1}
}

func (x *VendorEmailReceived) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *VendorEmailReceived) GetTraceParent() string {
	if x != nil {
		return x.TraceParent
	}
	return ""
}

func (x *VendorEmailReceived) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *VendorEmailReceived) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *VendorEmailReceived) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *VendorEmailReceived) GetCdcEmitTs() *timestamppb.Timestamp {
	if x != nil {
		return x.CdcEmitTs
	}
	return nil
}

func (x *VendorEmailReceived) GetSequenceEngineKey() uint64 {
	if x != nil {
		return x.SequenceEngineKey
	}
	return 0
}

func (x *VendorEmailReceived) GetVisualizationStage() VendorEmailReceived_VisualizationStage {
	if x != nil {
		return x.VisualizationStage
	}
	return VendorEmailReceived_VISUALIZATION_STAGE_UNSPECIFIED
}

func (x *VendorEmailReceived) GetIntentClassification() VendorEmailReceived_Intent {
	if x != nil {
		return x.IntentClassification
	}
	return VendorEmailReceived_INTENT_UNSPECIFIED
}

func (x *VendorEmailReceived) GetVendorEmail() string {
	if x != nil {
		return x.VendorEmail
	}
	return ""
}

func (x *VendorEmailReceived) GetMdmVendorId() string {
	if x != nil {
		return x.MdmVendorId
	}
	return ""
}

func (x *VendorEmailReceived) GetSecureSubjectUri() string {
	if x != nil {
		return x.SecureSubjectUri
	}
	return ""
}

func (x *VendorEmailReceived) GetSecureBodyUri() string {
	if x != nil {
		return x.SecureBodyUri
	}
	return ""
}

func (x *VendorEmailReceived) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

type HumanApprovalEvent struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TraceParent       string                 `protobuf:"bytes,2,opt,name=trace_parent,json=traceParent,proto3" json:"trace_parent,omitempty"`
	SequenceEngineKey uint64                 `protobuf:"varint,3,opt,name=sequence_engine_key,json=sequenceEngineKey,proto3" json:"sequence_engine_key,omitempty"`
	ApprovedBy        string                 `protobuf:"bytes,4,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HumanApprovalEvent) Reset() {
	*x = HumanApprovalEvent{}
	mi := &file_events_communication_v1_orchestration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HumanApprovalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanApprovalEvent) ProtoMessage() {}

func (x *HumanApprovalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_communication_v1_orchestration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanApprovalEvent.ProtoReflect.Descriptor instead.
func (*HumanApprovalEvent) Descriptor() ([]byte, []int) {
	return file_events_communication_v1_orchestration_proto_rawDescGZIP(), []int{2}
}

func (x *HumanApprovalEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *HumanApprovalEvent) GetTraceParent() string {
	if x != nil {
		return x.TraceParent
	}
	return ""
}

func (x *HumanApprovalEvent) GetSequenceEngineKey() uint64 {
	if x != nil {
		return x.SequenceEngineKey
	}
	return 0
}

func (x *HumanApprovalEvent) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

var File_events_communication_v1_orchestration_proto protoreflect.FileDescriptor

const file_events_communication_v1_orchestration_proto_rawDesc = "" +
	"\n" +
	"+events/communication/v1/orchestration.proto\x12\x19omniflow.communication.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\x95\x01\n" +
	"\n" +
	"Attachment\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\x12,\n" +
	"\x12secure_storage_uri\x18\x03 \x01(\tR\x10secureStorageUri\x12\x1f\n" +
	"\vsha256_hash\x18\x04 \x01(\tR\n" +
	"sha256Hash\"\x84\n" +
	"\n" +
	"\x13VendorEmailReceived\x12#\n" +
	"\bevent_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aeventId\x12T\n" +
	"\ftrace_parent\x18\x02 \x01(\tB1\xbaH.r,2*^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$R\vtraceParent\x12*\n" +
	"\faggregate_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vaggregateId\x12C\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"occurredAt\x12E\n" +
	"\fpublished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\vpublishedAt\x12:\n" +
	"\vcdc_emit_ts\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcdcEmitTs\x12.\n" +
	"\x13sequence_engine_key\x18\a \x01(\x04R\x11sequenceEngineKey\x12|\n" +
	"\x13visualization_stage\x18\b \x01(\x0e2A.omniflow.communication.v1.VendorEmailReceived.VisualizationStageB\b\xbaH\x05\x82\x01\x02\x10\x01R\x12visualizationStage\x12t\n" +
	"\x15intent_classification\x18\t \x01(\x0e25.omniflow.communication.v1.VendorEmailReceived.IntentB\b\xbaH\x05\x82\x01\x02\x10\x01R\x14intentClassification\x12*\n" +
	"\fvendor_email\x18\n" +
	" \x01(\tB\a\xbaH\x04r\x02`\x01R\vvendorEmail\x12+\n" +
	"\rmdm_vendor_id\x18\v \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vmdmVendorId\x126\n" +
	"\x12secure_subject_uri\x18\f \x01(\tB\b\xbaH\x05r\x03\x88\x01\x01R\x10secureSubjectUri\x120\n" +
	"\x0fsecure_body_uri\x18\r \x01(\tB\b\xbaH\x05r\x03\x88\x01\x01R\rsecureBodyUri\x12Q\n" +
	"\vattachments\x18\x0e \x03(\v2%.omniflow.communication.v1.AttachmentB\b\xbaH\x05\x92\x01\x02\x10\x19R\vattachments\"\xa6\x01\n" +
	"\x12VisualizationStage\x12#\n" +
	"\x1fVISUALIZATION_STAGE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cVISUALIZATION_STAGE_INGESTED\x10\x01\x12\"\n" +
	"\x1eVISUALIZATION_STAGE_CLASSIFIED\x10\x02\x12%\n" +
	"!VISUALIZATION_STAGE_ORCHESTRATING\x10\x03\"\x9a\x01\n" +
	"\x06Intent\x12\x16\n" +
	"\x12INTENT_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INTENT_INVOICE_SUBMISSION\x10\x01\x12\x1a\n" +
	"\x16INTENT_PAYMENT_DISPUTE\x10\x02\x12!\n" +
	"\x1dINTENT_PURCHASE_ORDER_INQUIRY\x10\x03\x12\x1a\n" +
	"\x16INTENT_GENERAL_SUPPORT\x10\x04\"\xa3\x01\n" +
	"\x12HumanApprovalEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12!\n" +
	"\ftrace_parent\x18\x02 \x01(\tR\vtraceParent\x12.\n" +
	"\x13sequence_engine_key\x18\x03 \x01(\x04R\x11sequenceEngineKey\x12\x1f\n" +
	"\vapproved_by\x18\x04 \x01(\tR\n" +
	"approvedByB5Z3omniflow/contracts/communication/v1;communicationv1b\x06proto3"

var (
	file_events_communication_v1_orchestration_proto_rawDescOnce sync.Once
	file_events_communication_v1_orchestration_proto_rawDescData []byte
)

func file_events_communication_v1_orchestration_proto_rawDescGZIP() []byte {
	file_events_communication_v1_orchestration_proto_rawDescOnce.Do(func() {
		file_events_communication_v1_orchestration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_communication_v1_orchestration_proto_rawDesc), len(file_events_communication_v1_orchestration_proto_rawDesc)))
	})
	return file_events_communication_v1_orchestration_proto_rawDescData
}

var file_events_communication_v1_orchestration_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_events_communication_v1_orchestration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_events_communication_v1_orchestration_proto_goTypes = []any{
	(VendorEmailReceived_VisualizationStage)(0), // 0: omniflow.communication.v1.VendorEmailReceived.VisualizationStage
	(VendorEmailReceived_Intent)(0),             // 1: omniflow.communication.v1.VendorEmailReceived.Intent
	(*Attachment)(nil),                          // 2: omniflow.communication.v1.Attachment
	(*VendorEmailReceived)(nil),                 // 3: omniflow.communication.v1.VendorEmailReceived
	(*HumanApprovalEvent)(nil),                  // 4: omniflow.communication.v1.HumanApprovalEvent
	(*timestamppb.Timestamp)(nil),               // 5: google.protobuf.Timestamp
}
var file_events_communication_v1_orchestration_proto_depIdxs = []int32{
	5, // 0: omniflow.communication.v1.VendorEmailReceived.occurred_at:type_name -> google.protobuf.Timestamp
	5, // 1: omniflow.communication.v1.VendorEmailReceived.published_at:type_name -> google.protobuf.Timestamp
	5, // 2: omniflow.communication.v1.VendorEmailReceived.cdc_emit_ts:type_name -> google.protobuf.Timestamp
	0, // 3: omniflow.communication.v1.VendorEmailReceived.visualization_stage:type_name -> omniflow.communication.v1.VendorEmailReceived.VisualizationStage
	1, // 4: omniflow.communication.v1.VendorEmailReceived.intent_classification:type_name -> omniflow.communication.v1.VendorEmailReceived.Intent
	2, // 5: omniflow.communication.v1.VendorEmailReceived.attachments:type_name -> omniflow.communication.v1.Attachment
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_events_communication_v1_orchestration_proto_init() }
func file_events_communication_v1_orchestration_proto_init() {
	if File_events_communication_v1_orchestration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_communication_v1_orchestration_proto_rawDesc), len(file_events_communication_v1_orchestration_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_communication_v1_orchestration_proto_goTypes,
		DependencyIndexes: file_events_communication_v1_orchestration_proto_depIdxs,
		EnumInfos:         file_events_communication_v1_orchestration_proto_enumTypes,
		MessageInfos:      file_events_communication_v1_orchestration_proto_msgTypes,
	}.Build()
	File_events_communication_v1_orchestration_proto = out.File
	file_events_communication_v1_orchestration_proto_goTypes = nil
	file_events_communication_v1_orchestration_proto_depIdxs = nil
}
