// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/procurement/v1/procurement.proto

package procurementv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PurchaseOrderDrafted is emitted when the drafting agent has produced a purchase order and it has
// been durably recorded. It is the first event in this system produced by an AI agent rather than
// by deterministic code, which is why it carries provenance fields the other contracts do not:
// a consumer must be able to tell what produced a PO, from which inputs, and under whose approval.
//
// Monetary values are strings, matching the inventory contracts: the wire format must not round.
type PurchaseOrderDrafted struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EventId     string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TraceParent string                 `protobuf:"bytes,2,opt,name=trace_parent,json=traceParent,proto3" json:"trace_parent,omitempty"`
	// The workflow this PO belongs to. Also the aggregate id on the outbox row.
	WorkflowId        string                 `protobuf:"bytes,3,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	OccurredAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	PublishedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	SequenceEngineKey uint64                 `protobuf:"varint,6,opt,name=sequence_engine_key,json=sequenceEngineKey,proto3" json:"sequence_engine_key,omitempty"`
	// Human-readable PO number, unique per PO.
	PoNumber    string               `protobuf:"bytes,7,opt,name=po_number,json=poNumber,proto3" json:"po_number,omitempty"`
	MdmVendorId string               `protobuf:"bytes,8,opt,name=mdm_vendor_id,json=mdmVendorId,proto3" json:"mdm_vendor_id,omitempty"`
	Currency    string               `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	Lines       []*PurchaseOrderLine `protobuf:"bytes,10,rep,name=lines,proto3" json:"lines,omitempty"`
	// Sum of all line extended amounts. Recomputed and checked by the orchestrator before the PO is
	// persisted — an agent is not trusted to do arithmetic.
	TotalAmount   string           `protobuf:"bytes,11,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Provenance    *AgentProvenance `protobuf:"bytes,12,opt,name=provenance,proto3" json:"provenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchaseOrderDrafted) Reset() {
	*x = PurchaseOrderDrafted{}
	mi := &file_events_procurement_v1_procurement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseOrderDrafted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseOrderDrafted) ProtoMessage() {}

func (x *PurchaseOrderDrafted) ProtoReflect() protoreflect.Message {
	mi := &file_events_procurement_v1_procurement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseOrderDrafted.ProtoReflect.Descriptor instead.
func (*PurchaseOrderDrafted) Descriptor() ([]byte, []int) {
	return file_events_procurement_v1_procurement_proto_rawDescGZIP(), []int{0}
}

func (x *PurchaseOrderDrafted) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PurchaseOrderDrafted) GetTraceParent() string {
	if x != nil {
		return x.TraceParent
	}
	return ""
}

func (x *PurchaseOrderDrafted) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *PurchaseOrderDrafted) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PurchaseOrderDrafted) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *PurchaseOrderDrafted) GetSequenceEngineKey() uint64 {
	if x != nil {
		return x.SequenceEngineKey
	}
	return 0
}

func (x *PurchaseOrderDrafted) GetPoNumber() string {
	if x != nil {
		return x.PoNumber
	}
	return ""
}

func (x *PurchaseOrderDrafted) GetMdmVendorId() string {
	if x != nil {
		return x.MdmVendorId
	}
	return ""
}

func (x *PurchaseOrderDrafted) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PurchaseOrderDrafted) GetLines() []*PurchaseOrderLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *PurchaseOrderDrafted) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *PurchaseOrderDrafted) GetProvenance() *AgentProvenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

type PurchaseOrderLine struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Sku         string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Quantity    string                 `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice   string                 `protobuf:"bytes,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	// quantity * unit_price. Verified server-side, never taken on the agent's word.
	ExtendedAmount string `protobuf:"bytes,5,opt,name=extended_amount,json=extendedAmount,proto3" json:"extended_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PurchaseOrderLine) Reset() {
	*x = PurchaseOrderLine{}
	mi := &file_events_procurement_v1_procurement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseOrderLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseOrderLine) ProtoMessage() {}

func (x *PurchaseOrderLine) ProtoReflect() protoreflect.Message {
	mi := &file_events_procurement_v1_procurement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseOrderLine.ProtoReflect.Descriptor instead.
func (*PurchaseOrderLine) Descriptor() ([]byte, []int) {
	return file_events_procurement_v1_procurement_proto_rawDescGZIP(), []int{1}
}

func (x *PurchaseOrderLine) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *PurchaseOrderLine) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PurchaseOrderLine) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PurchaseOrderLine) GetUnitPrice() string {
	if x != nil {
		return x.UnitPrice
	}
	return ""
}

func (x *PurchaseOrderLine) GetExtendedAmount() string {
	if x != nil {
		return x.ExtendedAmount
	}
	return ""
}

// AgentProvenance is the governance record that travels WITH the event, not just in a log.
//
// A procurement buyer's first question about an autonomously drafted PO is "what produced this, and
// can you prove it was reviewed?". Answering that from a log aggregator is not an answer; the
// provenance has to be part of the contract so every downstream consumer is forced to carry it.
type AgentProvenance struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Model   string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// SHA-256 of the exact prompt sent, hex-encoded. The prompt itself may contain vendor data, so
	// the hash travels on the bus and the body stays in the audit table.
	PromptSha256 string `protobuf:"bytes,3,opt,name=prompt_sha256,json=promptSha256,proto3" json:"prompt_sha256,omitempty"`
	// Links to the row in agent_decisions holding the full prompt, raw response, and cost.
	DecisionId       string `protobuf:"bytes,4,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	PromptTokens     uint32 `protobuf:"varint,5,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens uint32 `protobuf:"varint,6,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	// Micro-USD (1e-6 USD) to keep spend integral — floating-point money is a defect.
	CostMicroUsd uint64 `protobuf:"varint,7,opt,name=cost_micro_usd,json=costMicroUsd,proto3" json:"cost_micro_usd,omitempty"`
	// False when the value fell under the autonomous ceiling and no human reviewed it. A consumer
	// can then apply its own policy rather than assuming every PO was seen by a person.
	HumanApproved bool `protobuf:"varint,8,opt,name=human_approved,json=humanApproved,proto3" json:"human_approved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentProvenance) Reset() {
	*x = AgentProvenance{}
	mi := &file_events_procurement_v1_procurement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentProvenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentProvenance) ProtoMessage() {}

func (x *AgentProvenance) ProtoReflect() protoreflect.Message {
	mi := &file_events_procurement_v1_procurement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentProvenance.ProtoReflect.Descriptor instead.
func (*AgentProvenance) Descriptor() ([]byte, []int) {
	return file_events_procurement_v1_procurement_proto_rawDescGZIP(), []int{2}
}

func (x *AgentProvenance) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentProvenance) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentProvenance) GetPromptSha256() string {
	if x != nil {
		return x.PromptSha256
	}
	return ""
}

func (x *AgentProvenance) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *AgentProvenance) GetPromptTokens() uint32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *AgentProvenance) GetCompletionTokens() uint32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *AgentProvenance) GetCostMicroUsd() uint64 {
	if x != nil {
		return x.CostMicroUsd
	}
	return 0
}

func (x *AgentProvenance) GetHumanApproved() bool {
	if x != nil {
		return x.HumanApproved
	}
	return false
}

var File_events_procurement_v1_procurement_proto protoreflect.FileDescriptor

const file_events_procurement_v1_procurement_proto_rawDesc = "" +
	"\n" +
	"'events/procurement/v1/procurement.proto\x12\x17omniflow.procurement.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xd5\x05\n" +
	"\x14PurchaseOrderDrafted\x12#\n" +
	"\bevent_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aeventId\x12T\n" +
	"\ftrace_parent\x18\x02 \x01(\tB1\xbaH.r,2*^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$R\vtraceParent\x12)\n" +
	"\vworkflow_id\x18\x03 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"workflowId\x12C\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"occurredAt\x12E\n" +
	"\fpublished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\vpublishedAt\x12.\n" +
	"\x13sequence_engine_key\x18\x06 \x01(\x04R\x11sequenceEngineKey\x12$\n" +
	"\tpo_number\x18\a \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bpoNumber\x12+\n" +
	"\rmdm_vendor_id\x18\b \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vmdmVendorId\x12$\n" +
	"\bcurrency\x18\t \x01(\tB\b\xbaH\x05r\x03\x98\x01\x03R\bcurrency\x12M\n" +
	"\x05lines\x18\n" +
	" \x03(\v2*.omniflow.procurement.v1.PurchaseOrderLineB\v\xbaH\b\x92\x01\x05\b\x01\x10\xc8\x01R\x05lines\x12A\n" +
	"\ftotal_amount\x18\v \x01(\tB\x1e\xbaH\x1br\x192\x17^[0-9]+(\\.[0-9]{1,4})?$R\vtotalAmount\x12P\n" +
	"\n" +
	"provenance\x18\f \x01(\v2(.omniflow.procurement.v1.AgentProvenanceB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"provenance\"\x9e\x02\n" +
	"\x11PurchaseOrderLine\x12\x19\n" +
	"\x03sku\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03sku\x12*\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\xf4\x03R\vdescription\x12:\n" +
	"\bquantity\x18\x03 \x01(\tB\x1e\xbaH\x1br\x192\x17^[0-9]+(\\.[0-9]{1,4})?$R\bquantity\x12=\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\tB\x1e\xbaH\x1br\x192\x17^[0-9]+(\\.[0-9]{1,4})?$R\tunitPrice\x12G\n" +
	"\x0fextended_amount\x18\x05 \x01(\tB\x1e\xbaH\x1br\x192\x17^[0-9]+(\\.[0-9]{1,4})?$R\x0eextendedAmount\"\xda\x02\n" +
	"\x0fAgentProvenance\x12\"\n" +
	"\bagent_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\aagentId\x12\x1d\n" +
	"\x05model\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05model\x12:\n" +
	"\rprompt_sha256\x18\x03 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9a-f]{64}$R\fpromptSha256\x12)\n" +
	"\vdecision_id\x18\x04 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"decisionId\x12#\n" +
	"\rprompt_tokens\x18\x05 \x01(\rR\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x06 \x01(\rR\x10completionTokens\x12$\n" +
	"\x0ecost_micro_usd\x18\a \x01(\x04R\fcostMicroUsd\x12%\n" +
	"\x0ehuman_approved\x18\b \x01(\bR\rhumanApprovedB1Z/omniflow/contracts/procurement/v1;procurementv1b\x06proto3"

var (
	file_events_procurement_v1_procurement_proto_rawDescOnce sync.Once
	file_events_procurement_v1_procurement_proto_rawDescData []byte
)

func file_events_procurement_v1_procurement_proto_rawDescGZIP() []byte {
	file_events_procurement_v1_procurement_proto_rawDescOnce.Do(func() {
		file_events_procurement_v1_procurement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_procurement_v1_procurement_proto_rawDesc), len(file_events_procurement_v1_procurement_proto_rawDesc)))
	})
	return file_events_procurement_v1_procurement_proto_rawDescData
}

var file_events_procurement_v1_procurement_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_events_procurement_v1_procurement_proto_goTypes = []any{
	(*PurchaseOrderDrafted)(nil),  // 0: omniflow.procurement.v1.PurchaseOrderDrafted
	(*PurchaseOrderLine)(nil),     // 1: omniflow.procurement.v1.PurchaseOrderLine
	(*AgentProvenance)(nil),       // 2: omniflow.procurement.v1.AgentProvenance
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_events_procurement_v1_procurement_proto_depIdxs = []int32{
	3, // 0: omniflow.procurement.v1.PurchaseOrderDrafted.occurred_at:type_name -> google.protobuf.Timestamp
	3, // 1: omniflow.procurement.v1.PurchaseOrderDrafted.published_at:type_name -> google.protobuf.Timestamp
	1, // 2: omniflow.procurement.v1.PurchaseOrderDrafted.lines:type_name -> omniflow.procurement.v1.PurchaseOrderLine
	2, // 3: omniflow.procurement.v1.PurchaseOrderDrafted.provenance:type_name -> omniflow.procurement.v1.AgentProvenance
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_events_procurement_v1_procurement_proto_init() }
func file_events_procurement_v1_procurement_proto_init() {
	if File_events_procurement_v1_procurement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_procurement_v1_procurement_proto_rawDesc), len(file_events_procurement_v1_procurement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_procurement_v1_procurement_proto_goTypes,
		DependencyIndexes: file_events_procurement_v1_procurement_proto_depIdxs,
		MessageInfos:      file_events_procurement_v1_procurement_proto_msgTypes,
	}.Build()
	File_events_procurement_v1_procurement_proto = out.File
	file_events_procurement_v1_procurement_proto_goTypes = nil
	file_events_procurement_v1_procurement_proto_depIdxs = nil
}
