// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: events/inventory/v1/inventory.proto

package inventoryv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InventoryMovementReceived_MovementType int32

const (
	InventoryMovementReceived_MOVEMENT_TYPE_UNSPECIFIED InventoryMovementReceived_MovementType = 0
	InventoryMovementReceived_MOVEMENT_TYPE_RECEIPT     InventoryMovementReceived_MovementType = 1
	InventoryMovementReceived_MOVEMENT_TYPE_CONSUMPTION InventoryMovementReceived_MovementType = 2
	InventoryMovementReceived_MOVEMENT_TYPE_ADJUSTMENT  InventoryMovementReceived_MovementType = 3
)

// Enum value maps for InventoryMovementReceived_MovementType.
var (
	InventoryMovementReceived_MovementType_name = map[int32]string{
		0: "MOVEMENT_TYPE_UNSPECIFIED",
		1: "MOVEMENT_TYPE_RECEIPT",
		2: "MOVEMENT_TYPE_CONSUMPTION",
		3: "MOVEMENT_TYPE_ADJUSTMENT",
	}
	InventoryMovementReceived_MovementType_value = map[string]int32{
		"MOVEMENT_TYPE_UNSPECIFIED": 0,
		"MOVEMENT_TYPE_RECEIPT":     1,
		"MOVEMENT_TYPE_CONSUMPTION": 2,
		"MOVEMENT_TYPE_ADJUSTMENT":  3,
	}
)

func (x InventoryMovementReceived_MovementType) Enum() *InventoryMovementReceived_MovementType {
	p := new(InventoryMovementReceived_MovementType)
	*p = x
	return p
}

func (x InventoryMovementReceived_MovementType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InventoryMovementReceived_MovementType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (InventoryMovementReceived_MovementType) Type() protoreflect.EnumType {
	return &file_events_inventory_v1_inventory_proto_enumTypes[0]
}

func (x InventoryMovementReceived_MovementType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InventoryMovementReceived_MovementType.Descriptor instead.
func (InventoryMovementReceived_MovementType) EnumDescriptor() ([]byte, []int) {
	return file_events_inventory_v1_inventory_proto_rawDescGZIP(), []int{0, 0}
}

type InventoryMovementReceived struct {
	state             protoimpl.MessageState                 `protogen:"open.v1"`
	EventId           string                                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TraceParent       string                                 `protobuf:"bytes,2,opt,name=trace_parent,json=traceParent,proto3" json:"trace_parent,omitempty"`
	AggregateId       string                                 `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	OccurredAt        *timestamppb.Timestamp                 `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	PublishedAt       *timestamppb.Timestamp                 `protobuf:"bytes,5,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	CdcEmitTs         *timestamppb.Timestamp                 `protobuf:"bytes,6,opt,name=cdc_emit_ts,json=cdcEmitTs,proto3" json:"cdc_emit_ts,omitempty"`
	SequenceEngineKey uint64                                 `protobuf:"varint,7,opt,name=sequence_engine_key,json=sequenceEngineKey,proto3" json:"sequence_engine_key,omitempty"`
	MovementType      InventoryMovementReceived_MovementType `protobuf:"varint,8,opt,name=movement_type,json=movementType,proto3,enum=omniflow.inventory.v1.InventoryMovementReceived_MovementType" json:"movement_type,omitempty"`
	Sku               string                                 `protobuf:"bytes,9,opt,name=sku,proto3" json:"sku,omitempty"`
	MdmVendorId       string                                 `protobuf:"bytes,10,opt,name=mdm_vendor_id,json=mdmVendorId,proto3" json:"mdm_vendor_id,omitempty"`
	LocationId        string                                 `protobuf:"bytes,11,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Quantity          string                                 `protobuf:"bytes,12,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitCost          string                                 `protobuf:"bytes,13,opt,name=unit_cost,json=unitCost,proto3" json:"unit_cost,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InventoryMovementReceived) Reset() {
	*x = InventoryMovementReceived{}
	mi := &file_events_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryMovementReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryMovementReceived) ProtoMessage() {}

func (x *InventoryMovementReceived) ProtoReflect() protoreflect.Message {
	mi := &file_events_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryMovementReceived.ProtoReflect.Descriptor instead.
func (*InventoryMovementReceived) Descriptor() ([]byte, []int) {
	return file_events_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryMovementReceived) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *InventoryMovementReceived) GetTraceParent() string {
	if x != nil {
		return x.TraceParent
	}
	return ""
}

func (x *InventoryMovementReceived) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *InventoryMovementReceived) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *InventoryMovementReceived) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *InventoryMovementReceived) GetCdcEmitTs() *timestamppb.Timestamp {
	if x != nil {
		return x.CdcEmitTs
	}
	return nil
}

func (x *InventoryMovementReceived) GetSequenceEngineKey() uint64 {
	if x != nil {
		return x.SequenceEngineKey
	}
	return 0
}

func (x *InventoryMovementReceived) GetMovementType() InventoryMovementReceived_MovementType {
	if x != nil {
		return x.MovementType
	}
	return InventoryMovementReceived_MOVEMENT_TYPE_UNSPECIFIED
}

func (x *InventoryMovementReceived) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventoryMovementReceived) GetMdmVendorId() string {
	if x != nil {
		return x.MdmVendorId
	}
	return ""
}

func (x *InventoryMovementReceived) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *InventoryMovementReceived) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *InventoryMovementReceived) GetUnitCost() string {
	if x != nil {
		return x.UnitCost
	}
	return ""
}

type InventorySnapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId     string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	SnapshotDate   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=snapshot_date,json=snapshotDate,proto3" json:"snapshot_date,omitempty"`
	Sku            string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	MdmVendorId    string                 `protobuf:"bytes,4,opt,name=mdm_vendor_id,json=mdmVendorId,proto3" json:"mdm_vendor_id,omitempty"`
	LocationId     string                 `protobuf:"bytes,5,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	QtyOnHand      string                 `protobuf:"bytes,6,opt,name=qty_on_hand,json=qtyOnHand,proto3" json:"qty_on_hand,omitempty"`
	FifoTotalValue string                 `protobuf:"bytes,7,opt,name=fifo_total_value,json=fifoTotalValue,proto3" json:"fifo_total_value,omitempty"`
	MovingAvgCost  string                 `protobuf:"bytes,8,opt,name=moving_avg_cost,json=movingAvgCost,proto3" json:"moving_avg_cost,omitempty"`
	LastUpdatedAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InventorySnapshot) Reset() {
	*x = InventorySnapshot{}
	mi := &file_events_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventorySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventorySnapshot) ProtoMessage() {}

func (x *InventorySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_events_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventorySnapshot.ProtoReflect.Descriptor instead.
func (*InventorySnapshot) Descriptor() ([]byte, []int) {
	return file_events_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *InventorySnapshot) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *InventorySnapshot) GetSnapshotDate() *timestamppb.Timestamp {
	if x != nil {
		return x.SnapshotDate
	}
	return nil
}

func (x *InventorySnapshot) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *InventorySnapshot) GetMdmVendorId() string {
	if x != nil {
		return x.MdmVendorId
	}
	return ""
}

func (x *InventorySnapshot) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *InventorySnapshot) GetQtyOnHand() string {
	if x != nil {
		return x.QtyOnHand
	}
	return ""
}

func (x *InventorySnapshot) GetFifoTotalValue() string {
	if x != nil {
		return x.FifoTotalValue
	}
	return ""
}

func (x *InventorySnapshot) GetMovingAvgCost() string {
	if x != nil {
		return x.MovingAvgCost
	}
	return ""
}

func (x *InventorySnapshot) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

var File_events_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_events_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"#events/inventory/v1/inventory.proto\x12\x15omniflow.inventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\x95\a\n" +
	"\x19InventoryMovementReceived\x12#\n" +
	"\bevent_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aeventId\x12T\n" +
	"\ftrace_parent\x18\x02 \x01(\tB1\xbaH.r,2*^00-[0-9a-f]{32}-[0-9a-f]{16}-[0-9a-f]{2}$R\vtraceParent\x12*\n" +
	"\faggregate_id\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vaggregateId\x12C\n" +
	"\voccurred_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"occurredAt\x12E\n" +
	"\fpublished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\vpublishedAt\x12:\n" +
	"\vcdc_emit_ts\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcdcEmitTs\x12.\n" +
	"\x13sequence_engine_key\x18\a \x01(\x04R\x11sequenceEngineKey\x12l\n" +
	"\rmovement_type\x18\b \x01(\x0e2=.omniflow.inventory.v1.InventoryMovementReceived.MovementTypeB\b\xbaH\x05\x82\x01\x02\x10\x01R\fmovementType\x12\x19\n" +
	"\x03sku\x18\t \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03sku\x12+\n" +
	"\rmdm_vendor_id\x18\n" +
	" \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vmdmVendorId\x12(\n" +
	"\vlocation_id\x18\v \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"locationId\x128\n" +
	"\bquantity\x18\f \x01(\tB\x1c\xbaH\x19r\x172\x15^-?[0-9]+(\\.[0-9]+)?$R\bquantity\x127\n" +
	"\tunit_cost\x18\r \x01(\tB\x1a\xbaH\x17r\x152\x13^[0-9]+(\\.[0-9]+)?$R\bunitCost\"\x85\x01\n" +
	"\fMovementType\x12\x1d\n" +
	"\x19MOVEMENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15MOVEMENT_TYPE_RECEIPT\x10\x01\x12\x1d\n" +
	"\x19MOVEMENT_TYPE_CONSUMPTION\x10\x02\x12\x1c\n" +
	"\x18MOVEMENT_TYPE_ADJUSTMENT\x10\x03\"\x8d\x04\n" +
	"\x11InventorySnapshot\x12)\n" +
	"\vsnapshot_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\n" +
	"snapshotId\x12G\n" +
	"\rsnapshot_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\fsnapshotDate\x12\x19\n" +
	"\x03sku\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03sku\x12+\n" +
	"\rmdm_vendor_id\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vmdmVendorId\x12(\n" +
	"\vlocation_id\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"locationId\x12<\n" +
	"\vqty_on_hand\x18\x06 \x01(\tB\x1c\xbaH\x19r\x172\x15^-?[0-9]+(\\.[0-9]+)?$R\tqtyOnHand\x12D\n" +
	"\x10fifo_total_value\x18\a \x01(\tB\x1a\xbaH\x17r\x152\x13^[0-9]+(\\.[0-9]+)?$R\x0efifoTotalValue\x12B\n" +
	"\x0fmoving_avg_cost\x18\b \x01(\tB\x1a\xbaH\x17r\x152\x13^[0-9]+(\\.[0-9]+)?$R\rmovingAvgCost\x12J\n" +
	"\x0flast_updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\rlastUpdatedAtB-Z+omniflow/contracts/inventory/v1;inventoryv1b\x06proto3"

var (
	file_events_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_events_inventory_v1_inventory_proto_rawDescData []byte
)

func file_events_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_events_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_events_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_inventory_v1_inventory_proto_rawDesc), len(file_events_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_events_inventory_v1_inventory_proto_rawDescData
}

var file_events_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_events_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_inventory_v1_inventory_proto_goTypes = []any{
	(InventoryMovementReceived_MovementType)(0), // 0: omniflow.inventory.v1.InventoryMovementReceived.MovementType
	(*InventoryMovementReceived)(nil),           // 1: omniflow.inventory.v1.InventoryMovementReceived
	(*InventorySnapshot)(nil),                   // 2: omniflow.inventory.v1.InventorySnapshot
	(*timestamppb.Timestamp)(nil),               // 3: google.protobuf.Timestamp
}
var file_events_inventory_v1_inventory_proto_depIdxs = []int32{
	3, // 0: omniflow.inventory.v1.InventoryMovementReceived.occurred_at:type_name -> google.protobuf.Timestamp
	3, // 1: omniflow.inventory.v1.InventoryMovementReceived.published_at:type_name -> google.protobuf.Timestamp
	3, // 2: omniflow.inventory.v1.InventoryMovementReceived.cdc_emit_ts:type_name -> google.protobuf.Timestamp
	0, // 3: omniflow.inventory.v1.InventoryMovementReceived.movement_type:type_name -> omniflow.inventory.v1.InventoryMovementReceived.MovementType
	3, // 4: omniflow.inventory.v1.InventorySnapshot.snapshot_date:type_name -> google.protobuf.Timestamp
	3, // 5: omniflow.inventory.v1.InventorySnapshot.last_updated_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_events_inventory_v1_inventory_proto_init() }
func file_events_inventory_v1_inventory_proto_init() {
	if File_events_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_inventory_v1_inventory_proto_rawDesc), len(file_events_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_events_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_events_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_events_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_events_inventory_v1_inventory_proto = out.File
	file_events_inventory_v1_inventory_proto_goTypes = nil
	file_events_inventory_v1_inventory_proto_depIdxs = nil
}
